# Generated by Django 3.1 on 2020-08-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remdisivir', models.IntegerField()),
                ('FabiFlu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('l1beds', models.IntegerField()),
                ('l2beds', models.IntegerField()),
                ('l3beds', models.IntegerField()),
                ('ppe', models.IntegerField()),
                ('Mob', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.city')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.state'),
        ),
    ]
