# Generated by Django 3.1 on 2020-08-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='l1bedso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='l2bedso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='l3bedso',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
