# Generated by Django 3.1 on 2020-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20200829_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='med',
        ),
        migrations.AddField(
            model_name='hospital',
            name='FabiFlu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='Remdisivir',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
