# Generated by Django 3.1 on 2020-08-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_auto_20200829_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicine',
        ),
    ]
